# Generated by Django 4.1.5 on 2023-02-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='sección',
            new_name='seccion',
        ),
    ]
